name: Deploy Website
on: [push]
jobs:
  build-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing Python and pip
        run: |
          sudo apt install python3-pip
          python3 -m pip install -r ./.murmuration-ci/requirements.txt
      - name: Build the website
        run: |
          sudo chmod +x ./website/generate.py
          ./website/generate.py
      - name: Copy the static folder to the built website
        run: |
          cp -r ./website/static ./website/build/
          ls -la ./website/build
     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
            
      - name: Install terraform
        run: |
            wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install terraform

      - name: Terraform apply for the bucket
        run: |
          TERRAFORM_DIR="./.murmuration-ci/terraform"
          terraform -chdir="$TERRAFORM_DIR" init
          terraform -chdir="$TERRAFORM_DIR" apply -auto-approve
