name: Deploy Website
on: [push]
jobs:
  build-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing Python and pip
        run: |
          sudo apt install python3-pip
          python3 -m pip install -r ./.murmuration-ci/requirements.txt

      - name: Build the website
        run: |
          ROOT_DIR=$(pwd)
          cd ./website
          make all
          cd $ROOT_DIR
     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
            
      - name: Install terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform

      - name: Terraform apply for the bucket then upload to S3 bucket
        id: terraform
        run: |
          ROOT_DIR=$(pwd)
          TERRAFORM_DIR="./.murmuration-ci/terraform"
          cd $TERRAFORM_DIR
          terraform init
          terraform apply -auto-approve
          BUCKET_ENDPOINT=$(terraform output -raw bucket_endpoint)
          BUCKET_NAME=$(terraform output -raw bucket_name)
          
          cd $ROOT_DIR
          echo "Bucket name: $BUCKET_NAME"
          echo "Bucket endpoint: $BUCKET_ENDPOINT"
          aws s3 sync ./website/build s3://$BUCKET_NAME --delete
